# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Django Unleashed
description: >- # this means to ignore newlines until "baseurl:"
  The website for Django Unleashed, written by Andrew Pinkham and
  published by Sams, an imprint of Pearson.
author: Andrew Pinkham
author_site: 'http://AndrewsForge.com'
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://django-unleashed.com'
twitter_username: andrewsforge
github_username:  jambonrose

informit_link: 'http://click.linksynergy.com/link?id=h60Duu8ZWMA&offerid=145238.2146200&type=2&murl=http%3A%2F%2Fwww.informit.com%2Ftitle%2F9780321985071'
amazon_link: 'http://www.amazon.com/gp/product/0321985079/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=0321985079&linkCode=as2&tag=djangou-20&linkId=JSPV6SR6MR5YZ4RD'
barnesnoble_link: 'http://www.barnesandnoble.com/w/django-unleashed-andrew-pinkham/1120492919?ean=9780321985071'

# Build settings
source: src
destination: build
markdown: kramdown
highlighter: rouge

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
  input: GFM
  # https://github.com/jekyll/jekyll/pull/4090
  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    span:
      disable: true

plugins:
- jekyll-titles-from-headings

collections:
- errata

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
